const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('launcher', {
  appVersion: () => ipcRenderer.invoke('app:version'),
  updateStatus: () => ipcRenderer.invoke('update:status'),
  checkForUpdate: () => ipcRenderer.invoke('update:check'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  onUpdate: cb => ipcRenderer.on('update:status', (_e, s) => cb(s)),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: s => ipcRenderer.invoke('settings:set', s),
  listAccounts: () => ipcRenderer.invoke('accounts:list'),
  loginMicrosoft: () => ipcRenderer.invoke('accounts:loginMicrosoft'),
  addOffline: name => ipcRenderer.invoke('accounts:addOffline', name),
  selectAccount: id => ipcRenderer.invoke('accounts:select', id),
  removeAccount: id => ipcRenderer.invoke('accounts:remove', id),
  listVersions: () => ipcRenderer.invoke('versions:list'),
  openExternal: url => ipcRenderer.invoke('open:external', url),
  openFolder: () => ipcRenderer.invoke('folder:open'),
  launch: opts => ipcRenderer.invoke('game:launch', opts),
  kill: () => ipcRenderer.invoke('game:kill'),
  onProgress: cb => ipcRenderer.on('game:progress', (_e, p) => cb(p)),
  onLog: cb => ipcRenderer.on('game:log', (_e, t) => cb(t)),
  onState: cb => ipcRenderer.on('game:state', (_e, s) => cb(s)),

  // Paths of files dropped onto the window (File.path no longer exists in Electron).
  pathForFile: file => webUtils.getPathForFile(file),

  searchMods: q => ipcRenderer.invoke('mods:search', q),
  listMods: q => ipcRenderer.invoke('mods:list', q),
  installMod: q => ipcRenderer.invoke('mods:install', q),
  removeMod: q => ipcRenderer.invoke('mods:remove', q),
  toggleMod: q => ipcRenderer.invoke('mods:toggle', q),
  addMods: q => ipcRenderer.invoke('mods:add', q),
  openModsFolder: q => ipcRenderer.invoke('mods:openFolder', q),
  onModStatus: cb => ipcRenderer.on('mods:status', (_e, s) => cb(s)),

  searchPacks: q => ipcRenderer.invoke('packs:search', q),
  listPacks: q => ipcRenderer.invoke('packs:list', q),
  installPack: q => ipcRenderer.invoke('packs:install', q),
  removePack: q => ipcRenderer.invoke('packs:remove', q),
  togglePack: q => ipcRenderer.invoke('packs:toggle', q),
  addPacks: q => ipcRenderer.invoke('packs:add', q),
  openPacksFolder: q => ipcRenderer.invoke('packs:openFolder', q),
  packsmcHasKey: () => ipcRenderer.invoke('packsmc:hasKey'),
  packsmcSetKey: key => ipcRenderer.invoke('packsmc:setKey', key),
  packsmcSearch: q => ipcRenderer.invoke('packsmc:search', q),
  packsmcGet: q => ipcRenderer.invoke('packsmc:get', q),
  packsmcCancel: q => ipcRenderer.invoke('packsmc:cancel', q),
  onPacksmcAdded: cb => ipcRenderer.on('packsmc:added', (_e, r) => cb(r)),

  listModpacks: () => ipcRenderer.invoke('modpacks:list'),
  searchModpacks: q => ipcRenderer.invoke('modpacks:search', q),
  createModpack: q => ipcRenderer.invoke('modpacks:create', q),
  renameModpack: q => ipcRenderer.invoke('modpacks:rename', q),
  deleteModpack: q => ipcRenderer.invoke('modpacks:delete', q),
  openModpackFolder: q => ipcRenderer.invoke('modpacks:openFolder', q),
  installModpack: q => ipcRenderer.invoke('modpacks:installModrinth', q),
  importModpacks: q => ipcRenderer.invoke('modpacks:import', q),
  exportModpack: q => ipcRenderer.invoke('modpacks:export', q),
  importModpackLink: q => ipcRenderer.invoke('modpacks:importLink', q),
  classifyZips: files => ipcRenderer.invoke('files:classifyZips', files),
  curseforgeHasKey: () => ipcRenderer.invoke('curseforge:hasKey'),
  curseforgeSetKey: key => ipcRenderer.invoke('curseforge:setKey', key),
  onModpackStatus: cb => ipcRenderer.on('modpacks:status', (_e, s) => cb(s)),

  getBoost: () => ipcRenderer.invoke('boost:get'),
  setBoostBuiltin: q => ipcRenderer.invoke('boost:setBuiltin', q),
  addBoostMod: m => ipcRenderer.invoke('boost:addExtra', m),
  removeBoostMod: q => ipcRenderer.invoke('boost:removeMod', q),

  presenceStatus: () => ipcRenderer.invoke('presence:status'),
  setPresenceView: v => ipcRenderer.invoke('presence:view', v),
  onAccounts: cb => ipcRenderer.on('accounts:changed', (_e, a) => cb(a)),
});
