const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('launcher', {
  appVersion: () => ipcRenderer.invoke('app:version'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: s => ipcRenderer.invoke('settings:set', s),
  listAccounts: () => ipcRenderer.invoke('accounts:list'),
  loginMicrosoft: () => ipcRenderer.invoke('accounts:loginMicrosoft'),
  addOffline: name => ipcRenderer.invoke('accounts:addOffline', name),
  selectAccount: id => ipcRenderer.invoke('accounts:select', id),
  removeAccount: id => ipcRenderer.invoke('accounts:remove', id),
  listVersions: () => ipcRenderer.invoke('versions:list'),
  openExternal: url => ipcRenderer.invoke('open:external', url),
  openFolder: () => ipcRenderer.invoke('folder:open'),
  launch: opts => ipcRenderer.invoke('game:launch', opts),
  kill: () => ipcRenderer.invoke('game:kill'),
  onProgress: cb => ipcRenderer.on('game:progress', (_e, p) => cb(p)),
  onLog: cb => ipcRenderer.on('game:log', (_e, t) => cb(t)),
  onState: cb => ipcRenderer.on('game:state', (_e, s) => cb(s)),
  searchMods: q => ipcRenderer.invoke('mods:search', q),
  listMods: q => ipcRenderer.invoke('mods:list', q),
  installMod: q => ipcRenderer.invoke('mods:install', q),
  removeMod: q => ipcRenderer.invoke('mods:remove', q),
  toggleMod: q => ipcRenderer.invoke('mods:toggle', q),
  openModsFolder: q => ipcRenderer.invoke('mods:openFolder', q),
  onModStatus: cb => ipcRenderer.on('mods:status', (_e, s) => cb(s)),
  presenceStatus: () => ipcRenderer.invoke('presence:status'),
  setPresenceView: v => ipcRenderer.invoke('presence:view', v),
  onAccounts: cb => ipcRenderer.on('accounts:changed', (_e, a) => cb(a)),
});
